ALTER TABLE products ADD COLUMN unit_price DECIMAL(12,2);
ALTER TABLE products ADD COLUMN stock_quantity INT NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN ordering_enabled BOOLEAN NOT NULL DEFAULT TRUE;
CREATE TABLE orders (
 id BIGINT AUTO_INCREMENT PRIMARY KEY, order_number VARCHAR(32) NOT NULL UNIQUE,
 visitor_id VARCHAR(80) NOT NULL, customer_name VARCHAR(160) NOT NULL,
 email VARCHAR(180) NOT NULL, phone VARCHAR(40) NOT NULL,
 fulfillment_method VARCHAR(20) NOT NULL, payment_method VARCHAR(30) NOT NULL,
 address_line VARCHAR(255) NOT NULL, city VARCHAR(120) NOT NULL, state VARCHAR(120) NOT NULL,
 postal_code VARCHAR(20) NOT NULL, notes TEXT NOT NULL, status VARCHAR(30) NOT NULL,
 subtotal DECIMAL(12,2) NOT NULL, delivery_fee DECIMAL(12,2) NOT NULL, total DECIMAL(12,2) NOT NULL,
 created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL
);
CREATE TABLE order_items (
 id BIGINT AUTO_INCREMENT PRIMARY KEY, order_id BIGINT NOT NULL REFERENCES orders(id),
 product_id BIGINT REFERENCES products(id) ON DELETE SET NULL, sku VARCHAR(60) NOT NULL,
 product_name VARCHAR(180) NOT NULL, price_label VARCHAR(80) NOT NULL,
 unit_price DECIMAL(12,2) NOT NULL, quantity INT NOT NULL, line_total DECIMAL(12,2) NOT NULL,
 created_at DATETIME NOT NULL
);
CREATE TABLE sync_state (topic VARCHAR(40) PRIMARY KEY, version BIGINT NOT NULL DEFAULT 0);
